In [65]:
import pandas as pd
import tensorflow 
from tensorflow import keras
from sklearn.preprocessing import MinMaxScaler

In [66]:
df=pd.read_csv("/kaggle/input/multiple-linear-regression-dataset/multiple_linear_regression_dataset.csv")

In [67]:
df

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [76]:
x=df.drop("income",axis="columns")
y=df["income"]

In [77]:
sx=MinMaxScaler()
sy=MinMaxScaler()
x=sx.fit_transform(x)
y=sy.fit_transform(y.values.reshape(df.shape[0],1))

In [70]:
import numpy as np
number_of_features=x.shape[1]
w=np.ones(number_of_features)
w

array([1., 1.])

In [71]:
def gradient_descent(x,y,epochs,lr=0.01):
    number_of_features=x.shape[1]
    w=np.ones(number_of_features)
    b=0
    total_samples=x.shape[0]
    
    total_cost=[]
    epoch=[]
    
    for i in range(epochs):
        predict=np.dot(w,x.T)+b
        
        dw=-(2/total_samples)*(x.T.dot(y-predict))
        db=-(2/total_samples)*np.sum(y-predict)
        w=w-lr*dw
        b=b-lr*db
        print(dw)
        cost=np.mean(np.square(y-predict))
        if i%10==0:
            total_cost.append(cost)
            epoch.append(i)
    return w,b,cost,total_cost,epoch
    

In [72]:
w,b,cost,total_cost,epoch=gradient_descent(x,y.reshape(y.shape[0]),500)

[0.59263463 0.38486912]
[0.57913122 0.37550478]
[0.56599196 0.36639279]
[0.55320695 0.35752629]
[0.54076653 0.34889859]
[0.52866133 0.34050319]
[0.51688221 0.33233376]
[0.50542031 0.32438416]
[0.49426698 0.31664841]
[0.48341382 0.30912068]
[0.47285267 0.3017953 ]
[0.46257557 0.29466678]
[0.4525748  0.28772976]
[0.44284282 0.28097902]
[0.43337233 0.27440949]
[0.4241562  0.26801624]
[0.41518751 0.26179448]
[0.40645953 0.25573953]
[0.3979657  0.24984687]
[0.38969965 0.24411207]
[0.38165519 0.23853083]
[0.37382628 0.23309898]
[0.36620705 0.22781246]
[0.3587918 0.2226673]
[0.35157498 0.21765967]
[0.34455118 0.21278582]
[0.33771516 0.20804212]
[0.33106181 0.20342501]
[0.32458614 0.19893106]
[0.31828334 0.19455692]
[0.31214869 0.19029933]
[0.30617762 0.18615512]
[0.30036568 0.1821212 ]
[0.29470854 0.17819458]
[0.28920199 0.17437233]
[0.28384193 0.17065162]
[0.27862438 0.16702969]
[0.27354545 0.16350385]
[0.26860139 0.16007148]
[0.26378852 0.15673006]
[0.25910326 0.15347709]
[0.25454216 0.1503

In [80]:
def predict(age,experience,w,b):
    scaledx=sx.transform([[age,experience]])[0]
    scaled_price=w[0]*scaledx[0]+w[1]*scaledx[1]+b
    return sy.inverse_transform([[scaled_price]])[0][0]
print(w,b)
predict(39,8,w,b)

[0.44987932 0.75113794] -0.11277113759915432


/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


42913.227206493655

In [82]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=5)

In [110]:
model=keras.Sequential([
    keras.layers.Dense(3,input_shape=(X_train.shape[1],),activation="relu"),
    keras.layers.Dense(1)
    
])
model.compile(
optimizer="sgd",
loss="mean_squared_error",
metrics=["accuracy"])


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [111]:
model.fit(X_train,y_train,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 473ms/step - accuracy: 0.0625 - loss: 0.1789
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.0625 - loss: 0.1724
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0625 - loss: 0.1661
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0625 - loss: 0.1602
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0625 - loss: 0.1546
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0625 - loss: 0.1492
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0625 - loss: 0.1440
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0625 - loss: 0.1391
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0625 - loss: 0.1345
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0625 - loss: 0.1300
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0625 - loss: 0.1258
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.0625 - l

In [105]:
ypred=model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


In [106]:
ypred=sy.inverse_transform(ypred)

In [107]:
ypred

array([[39789.043],
       [41377.7  ],
       [41932.77 ],
       [44070.89 ]], dtype=float32)

In [108]:
sfw=sx.inverse_transform(X_test)

In [109]:
sfw

array([[47.,  2.],
       [51.,  7.],
       [23.,  1.],
       [37., 10.]])