In [1]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from tensorflow import keras 
from sklearn.model_selection import train_test_split

2024-07-20 02:13:41.782063: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-20 02:13:41.782136: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-20 02:13:41.783887: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
df=pd.read_csv("/kaggle/input/regression-dataset-for-household-income-analysis/data.csv")

In [3]:
df

Age Education_Level  Occupation  Number_of_Dependents  Location  \
0      56        Master's  Technology                     5     Urban   
1      69     High School     Finance                     0     Urban   
2      46      Bachelor's  Technology                     1     Urban   
3      32     High School      Others                     2     Urban   
4      60      Bachelor's     Finance                     3     Urban   
...   ...             ...         ...                   ...       ...   
9995   58     High School      Others                     0  Suburban   
9996   23        Master's  Technology                     3     Urban   
9997   41       Doctorate   Education                     3     Urban   
9998   44     High School   Education                     0     Urban   
9999   37     High School  Healthcare                     0  Suburban   

      Work_Experience Marital_Status Employment_Status  Household_Size  \
0                  21        Married         Full-time               7   
1                   4         Single         Full-time               7   
2                   1         Single         Full-time               7   
3                  32        Married         Full-time               1   
4                  15        Married     Self-employed               4   
...               ...            ...               ...             ...   
9995               26       Divorced         Full-time               6   
9996               16       Divorced         Full-time               1   
9997               50         Single         Full-time               4   
9998                3        Married         Part-time               1   
9999               48        Married         Part-time               7   

     Homeownership_Status     Type_of_Housing  Gender  \
0                     Own           Apartment    Male   
1                     Own           Apartment    Male   
2                     Own  Single-family home  Female   
3                     Own           Apartment  Female   
4                     Own           Townhouse    Male   
...                   ...                 ...     ...   
9995                  Own           Townhouse  Female   
9996                  Own  Single-family home  Female   
9997                  Own  Single-family home  Female   
9998                  Own  Single-family home    Male   
9999                 Rent  Single-family home    Male   

     Primary_Mode_of_Transportation   Income  
0                    Public transit    72510  
1                            Biking    75462  
2                               Car    71748  
3                               Car    74520  
4                           Walking   640210  
...                             ...      ...  
9995                            Car    74994  
9996                         Biking    72676  
9997                 Public transit  2684820  
9998                         Biking    57955  
9999                 Public transit  1131084  

[10000 rows x 14 columns]

In [4]:
for columns in df:
    print(columns,len(df[columns].unique()))

Age 53
Education_Level 4
Occupation 5
Number_of_Dependents 6
Location 3
Work_Experience 51
Marital_Status 3
Employment_Status 3
Household_Size 7
Homeownership_Status 2
Type_of_Housing 3
Gender 2
Primary_Mode_of_Transportation 4
Income 7667


In [5]:
columns=["Education_Level","Occupation","Location","Marital_Status","Employment_Status","Homeownership_Status","Type_of_Housing","Gender","Primary_Mode_of_Transportation"]

In [15]:
df=pd.get_dummies(df).astype(int)

In [20]:

num_columns=["Age","Number_of_Dependents","Work_Experience","Household_Size"]
xs=MinMaxScaler()
df[num_columns]=xs.fit_transform(df[num_columns])

In [21]:
df

Age  Number_of_Dependents  Work_Experience  Household_Size  \
0     0.730769                   1.0             0.42        1.000000   
1     0.980769                   0.0             0.08        1.000000   
2     0.538462                   0.2             0.02        1.000000   
3     0.269231                   0.4             0.64        0.000000   
4     0.807692                   0.6             0.30        0.500000   
...        ...                   ...              ...             ...   
9995  0.769231                   0.0             0.52        0.833333   
9996  0.096154                   0.6             0.32        0.000000   
9997  0.442308                   0.6             1.00        0.500000   
9998  0.500000                   0.0             0.06        0.000000   
9999  0.365385                   0.0             0.96        1.000000   

       Income  Education_Level_Bachelor's  Education_Level_Doctorate  \
0       72510                           0                          0   
1       75462                           0                          0   
2       71748                           1                          0   
3       74520                           0                          0   
4      640210                           1                          0   
...       ...                         ...                        ...   
9995    74994                           0                          0   
9996    72676                           0                          0   
9997  2684820                           0                          1   
9998    57955                           0                          0   
9999  1131084                           0                          0   

      Education_Level_High School  Education_Level_Master's  \
0                               0                         1   
1                               1                         0   
2                               0                         0   
3                               1                         0   
4                               0                         0   
...                           ...                       ...   
9995                            1                         0   
9996                            0                         1   
9997                            0                         0   
9998                            1                         0   
9999                            1                         0   

      Occupation_Education  ...  Homeownership_Status_Rent  \
0                        0  ...                          0   
1                        0  ...                          0   
2                        0  ...                          0   
3                        0  ...                          0   
4                        0  ...                          0   
...                    ...  ...                        ...   
9995                     0  ...                          0   
9996                     0  ...                          0   
9997                     1  ...                          0   
9998                     1  ...                          0   
9999                     0  ...                          1   

      Type_of_Housing_Apartment  Type_of_Housing_Single-family home  \
0                             1                                   0   
1                             1                                   0   
2                             0                                   1   
3                             1                                   0   
4                             0                                   0   
...                         ...                                 ...   
9995                          0                                   0   
9996                          0                                   1   
9997                          0                                   1   
9998                          0                          

In [23]:
x=df.drop("Income",axis=1)
y=df["Income"]


In [26]:
sy=MinMaxScaler()
y=sy.fit_transform(y.values.reshape(df.shape[0],1))

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [38]:
import tensorflow as tp
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout
model=keras.Sequential([
    keras.layers.Dense(32,input_shape=(x_train.shape[1],),activation="relu"),
    keras.layers.Dense(15,activation="relu"),
    keras.layers.Dense(1)

])
model.compile(
    optimizer="sgd",
    loss="mean_squared_error",
    metrics=[keras.metrics.RootMeanSquaredError()])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [39]:
model.fit(x_train,y_train,epochs=250)

Epoch 1/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0665 - root_mean_squared_error: 0.2549
Epoch 2/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0391 - root_mean_squared_error: 0.1977
Epoch 3/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0355 - root_mean_squared_error: 0.1884
Epoch 4/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0337 - root_mean_squared_error: 0.1836
Epoch 5/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0349 - root_mean_squared_error: 0.1868
Epoch 6/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0335 - root_mean_squared_error: 0.1830
Epoch 7/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0341 - root_mean_squared_error: 0.1846
Epoch 8/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0327 - root_mean_squared_error: 0.1808
Epoch 9/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0331 - root_mean_squared_error: 0.1818
Epoch 10/250
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0338 - root_mean_s

In [40]:
y_pred=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [41]:
y_pred

array([[0.0848272 ],
       [0.10585465],
       [0.11386106],
       ...,
       [0.05845204],
       [0.09720995],
       [0.06012208]], dtype=float32)

In [42]:
values=sy.inverse_transform(y_test)
values

array([[3200368.],
       [  70876.],
       [7716188.],
       ...,
       [7215570.],
       [  54853.],
       [  69137.]])

In [43]:
output=sy.inverse_transform(y_pred)
output

array([[ 876052.44],
       [1085518.  ],
       [1165274.  ],
       ...,
       [ 613315.56],
       [ 999403.5 ],
       [ 629951.7 ]], dtype=float32)